# Generated by Django 3.1.4 on 2021-10-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
